blogs/urls.py
from django.urls import path
from . import views

app_name = "blogs"
urlpatterns = [
    path('', views.all_blogs, name="all_blogs"),
    path('<int:blog_id>/', views.details, name="details")
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from projects import views

urlpatterns = [
    path('admin/', admin.site.urls),   # User name: mobeen, Password: mobeen007
    path('', views.home, name="home"),
    path('blog/', include('blogs.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from datetime import date


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField(default=date.today)
    description = models.TextField()

    def __str__(self):
        return self.title
    

projects/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to="projects/images")
    url = models.URLField(blank=True)  # blank=True means optional
    
    def __str__(self):
        return self.title 
    

blogs/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.

def all_blogs(request):
    blogs = Blog.objects.order_by("-date") # Sort in descending order on the basis of date
    return render(request, "blogs/all_blogs.html", {"blogs": blogs})

def details(request, blog_id):
    details = get_object_or_404(Blog, pk=blog_id)
    return render(request, "blogs/details.html", {"details": details})

projects/views.py
from django.shortcuts import render
# from django.http import HttpResponse
from .models import Project

# Create your views here.

def home(request):
    projects = Project.objects.all()
    return render(request, "projects/home.html", {"projects": projects})

blogs/templates/blogs/all_blogs.html
{% extends "projects/base.html" %}

{% block content %}

<h1>Blogs</h1>

<h2>Mobeen has written {{ blogs.count }} blog{{ blogs.count|pluralize}}</h2>

{% for blog in blogs %}

<a href="{% url 'blogs:details' blog.id %}">
    <h3>{{ blog.title }}</h3>
</a>
<h5>{{ blog.date|date:'M d Y' }}</h5>
<p>{{ blog.description|striptags|truncatechars:30 }}</p> <!-- use striptags to remove html tags -->

{% endfor %}

{% endblock %}

blogs/templates/blogs/details.html
{% extends "projects/base.html" %}

{% block content %}

<h1>{{ details.title }}</h1>

<h3>{{ details.date|date:'F jS Y' }}</h3>

<p>{{ details.description|safe }}</p>  <!-- safe is used when we need to process the html tags -->

{% endblock %}

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      
    {% block content %}{% endblock %}  <!-- content can be replaced by any other word -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
</body>

</html>

projects/templates/projects/home.html
{% extends "projects/base.html" %}

{% block content %}

<h1>Welcome</h1>

{% load static %}

{% for project in projects %}

<a href="{% static 'projects/CV - Mobeen Aslam.pdf' %}">Resume</a>
<a href="{% url 'blogs:all_blogs' %}">Blogs</a>
<br>
<img src="{% static 'projects/Capture1.jpg' %}" width="800">
<h2>{{ project.title }}</h2>
<h4>{{ project.description }}</h4>
<img src="{{ project.image.url }}">

{% if project.url %}
<br>
<a href="{{ project.url }}">Link</a>
{% endif %}

{% endfor %}

{% endblock %}